image: gitpod/workspace-android

tasks:
  - name: Setup Android Environment
    init: |
      # 设置Android SDK环境变量
      export ANDROID_HOME=/opt/android-sdk-linux
      export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      
      # 创建local.properties文件
      echo "sdk.dir=$ANDROID_HOME" > local.properties
      
      # 设置gradlew权限
      chmod +x gradlew
      
      # 清理项目
      ./gradlew clean
      
    command: |
      echo "🚀 Android开发环境已准备就绪！"
      echo "📱 运行以下命令构建APK："
      echo "   ./gradlew assembleDebug"
      echo "   ./gradlew assembleRelease"
      echo ""
      echo "📁 APK文件将生成在："
      echo "   app/build/outputs/apk/debug/app-debug.apk"
      echo "   app/build/outputs/apk/release/app-release-unsigned.apk"

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-gradle
